### PR TITLE
OCDS: New section & 'Getting To Done' guidance

### PR DESCRIPTION
**Pull request by robredpath**
@Bjwebb @kindly @odscjames @rhiaro how does this work as an attempt to document what's behind the DoD, and some procedures?

I talked with the OC analysts on Monday and they confirmed that CRM tickets are the best way to contact them

### CODE REVIEW

**Review by Bjwebb — DISMISSED** [review]

**Comment by robredpath** [comment]
WAWD4ODSC comments - add titles to examples 

Also note - need to add to index file

**Comment by odscjames** [comment]
It looks good, but should it be in reference rather than how to?  Most of it isn't a set of instructions

In https://opendataservices.gitbook.io/developer-docs/how-to-guides/add-black-isort-existing-repo I tried to link between that and the relevant reference page (See: Add .isort.cfg). This is in order to avoid to much duplication and the possibility of things getting out of sync; maybe split like that?

**Comment by robredpath** [comment]
Thanks, both. I've made some updates in response:
- Each section is now more of a how-to using the First, Then, Finally format 
- I've made it clear that it's not mandatory to do things this way, but this embodies some collective learning

I've not added it to the index yet because I'm still unsure of whether we have consensus around where it should go. If we're broadly happy with the how-to format then I'll add it there.

**Comment by odscjames** [comment]
Following "perfect enemy of better" let's put it in "how to" as you suggest and we can review later how people use it.

With my OCDS hat on, the only bit I'm not sure about is the line between notification/asking for explicit action from analysts. I'm not sure what Analysts would prefer here, but we can put this in now and try and work that out over time.

**Comment by robredpath** [comment]
@Bjwebb @odscjames please can one of you approve this so I can merge it?

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
