### PR TITLE
Add Git Practices as agreed at meeting 14th feb 2020

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by odscjames** [comment]
Hey all, this is my attempt to write up the meeting we had - it might be good to get approval from a few people before merging, as there is a lot here. (Or comments/feedback, of course)

**Comment by Lathrisk** [comment]
Is it worth adding something about the `.gitmessage` templates? They're pretty trivial to set up so maybe it's just a bonus 'if you can be bothered' extra that doesn't need to be included in the actual 
docs.

i.e.

```bash
cat <<EOT > .gitmessage 
#<module/submodule/file/some logical name to make it uniquely identifiable in the codebase>: <Change summary message>
unique_name: summary_msg

#<Longer message if needed to describe the change>
body_msg

#<Full URLs: github issues, pull requests if applicable>
urls
EOT
git config --global commit.template ~/.gitmessage
```

**Review by Lathrisk — DISMISSED** [review]
Otherwise it looks good to me, and covers everything we talked about (AFAIR).

**Review by Bjwebb — DISMISSED** [review]

**Comment by Bjwebb** [comment]
I would like to see the `.gitmessage` template in this docs repo (but not a blocker for this PR).

**Comment by odscjames** [comment]
@Lathrisk @Bjwebb Thanks! I just added a section on commit templates in a new commit.

**Review by Bjwebb — DISMISSED** [review]

**Review by Lathrisk — DISMISSED** [review]

**Review by michaelwood — DISMISSED** [review]
Approved, though if you want to be exacting on your 94ca5beb56f6f736cae3dabd6f36c970ba2ccba2 commit message format here, usually the identifier is in lowercase in the subject 
> The subject line should contain a logical module identifier of the scope of the changes that uniquely identifies it in lower case and then a short sentence to describe the changes.

and then the rest of the sentence starts with a capital letter e.g.
```
git: Add git commit template link

Added sub-headers to commit template section, as it was getting a bit long
```

**Comment by odscjames** [comment]
I see :-) I do have that in the actual examples on the page tho?

*  tests: Add test blah to make sure blah-de blah doesn’t regress 
*  pythonversions: Drop Python 2 support 
*  ocdsschema: Upgrade OCDS schema version and move standards site to SSL.

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
